baseURL = "https://jonathanleitetxr.github.io/Blog/"
defaultContentLanguage = "fr"
languageCode = "fr"

title = "AIDE"

theme = "gokarna"

publishDir = "docs"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
    description = "Un blog pour les étudiants"
    footer = ""

    # URL for the avatar on homepage
    avatarURL = "/univ.png"

    # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
    avatarSize = "size-xl"

    accentColor = "#08F"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"

    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1


  [[menu.main]]
    identifier = "activités"
    name = "Activités"
    url = "/activités/"
    weight = 5

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 4


  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    url = "https://github.com"
    weight = 3



    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
